Repository FeixiDev/VersaTEL_G1_Code, pull requests merged in 2020-06, with the labels that each got.

#39 Paul View the current version of the software
  Config.ini
  GetConfig.py
  Main.py
  sys_config.ini
Labels: Normal, enhancement

#36 Paul The configuration file is modified into two different configuration files
  Config.ini
  GetConfig.py
  sys_config.ini
Labels: Low, enhancement

#28 request_optimize-getConfig
  Config.ini
  GetConfig.py
  Monitor.py
Labels: Low, enhancement

#43 Anders：optimize thread functionality and handle keyboard exceptions
  Monitor.py
Labels: enhancement
